---
deployment:
  tasks:
    - export SOURCEPATH=/home/ovc8geqrq4s4/repositories/MVA_NACL/public
    - export DEPLOYPATH=/home/ovc8geqrq4s4/public_html/naclburhanpur.com
    - /bin/rsync -avh --delete $SOURCEPATH/ $DEPLOYPATH/
    - echo "Deployment completed successfully"
