---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ovc8geqrq4s4/public_html/naclburhanpurbur.com
    - /bin/rsync -avh --delete ./public/ $DEPLOYPATH/
    - echo "Deployment completed successfully"
