---
deployment:
  tasks:
    - DEPLOYPATH="/home/ovc8geqrq4s4/public_html/naclburhanpur.com"
    - REPOPATH="/home/ovc8geqrq4s4/repositories/MVA_NACL1"
    - cd "$REPOPATH/public"
    - /bin/rsync -avh --delete ./ "$DEPLOYPATH/"
    - echo "Deployment completed successfully"
